# plugins
curl -L https://cdn.jsdelivr.net/npm/docsify@4/lib/themes/vue.css --create-dirs -o ./doc/static/npm/docsify@4/lib/themes/vue.css
curl -L https://unpkg.com/docsify-toc@1.0.0/dist/toc.css --create-dirs -o ./doc/static/docsify-toc@1.0.0/dist/toc.css
curl -L https://cdn.jsdelivr.net/npm/docsify-darklight-theme@latest/dist/style.min.css --create-dirs -o ./doc/static/npm/docsify-darklight-theme@latest/dist/style.min.css
curl -L https://cdn.jsdelivr.net/npm/docsify-darklight-theme@latest/icons/sun.svg --create-dirs -o ./doc/static/npm/docsify-darklight-theme@latest/icons/sun.svg
curl -L https://cdn.jsdelivr.net/npm/docsify/lib/docsify.min.js --create-dirs -o ./doc/static/npm/docsify/lib/docsify.min.js
curl -L https://cdn.jsdelivr.net/npm/docsify/lib/plugins/search.min.js --create-dirs -o ./doc/static/npm/docsify/lib/plugins/search.min.js
curl -L https://unpkg.com/docsify-toc@1.0.0/dist/toc.js --create-dirs -o ./doc/static/docsify-toc@1.0.0/dist/toc.js
curl -L https://cdn.jsdelivr.net/npm/docsify-darklight-theme@latest/dist/index.min.js --create-dirs -o ./doc/static/npm/docsify-darklight-theme@latest/dist/index.min.js
curl -L https://unpkg.com/@markbattistella/docsify-sidebarfooter@latest --create-dirs -o ./doc/static/@markbattistella/docsify-sidebarfooter@latest
curl -L https://unpkg.com/docsify-copy-code --create-dirs -o ./doc/static/docsify-copy-code
curl -L https://unpkg.com/docsify-footer-enh/dist/docsify-footer-enh.min.js --create-dirs -o ./doc/static/docsify-footer-enh/dist/docsify-footer-enh.min.js
curl -L https://cdn.jsdelivr.net/npm/docsify-sidebar-collapse/dist/docsify-sidebar-collapse.min.js --create-dirs -o ./doc/static/npm/docsify-sidebar-collapse/dist/docsify-sidebar-collapse.min.js
curl -L https://cdn.jsdelivr.net/npm/docsify-sidebar-collapse/dist/sidebar.min.css --create-dirs -o ./doc/static/npm/docsify-sidebar-collapse/dist/sidebar.min.css

# code highlighting
curl -L https://unpkg.com/prismjs/components/prism-abap.min.js --create-dirs -o ./doc/static/prismjs/components/prism-abap.min.js
curl -L https://unpkg.com/prismjs/components/prism-abnf.min.js --create-dirs -o ./doc/static/prismjs/components/prism-abnf.min.js
curl -L https://unpkg.com/prismjs/components/prism-actionscript.min.js --create-dirs -o ./doc/static/prismjs/components/prism-actionscript.min.js
curl -L https://unpkg.com/prismjs/components/prism-ada.min.js --create-dirs -o ./doc/static/prismjs/components/prism-ada.min.js
curl -L https://unpkg.com/prismjs/components/prism-agda.min.js --create-dirs -o ./doc/static/prismjs/components/prism-agda.min.js
curl -L https://unpkg.com/prismjs/components/prism-al.min.js --create-dirs -o ./doc/static/prismjs/components/prism-al.min.js
curl -L https://unpkg.com/prismjs/components/prism-antlr4.min.js --create-dirs -o ./doc/static/prismjs/components/prism-antlr4.min.js
curl -L https://unpkg.com/prismjs/components/prism-apacheconf.min.js --create-dirs -o ./doc/static/prismjs/components/prism-apacheconf.min.js
curl -L https://unpkg.com/prismjs/components/prism-apex.min.js --create-dirs -o ./doc/static/prismjs/components/prism-apex.min.js
curl -L https://unpkg.com/prismjs/components/prism-apl.min.js --create-dirs -o ./doc/static/prismjs/components/prism-apl.min.js
curl -L https://unpkg.com/prismjs/components/prism-applescript.min.js --create-dirs -o ./doc/static/prismjs/components/prism-applescript.min.js
curl -L https://unpkg.com/prismjs/components/prism-aql.min.js --create-dirs -o ./doc/static/prismjs/components/prism-aql.min.js
curl -L https://unpkg.com/prismjs/components/prism-arduino.min.js --create-dirs -o ./doc/static/prismjs/components/prism-arduino.min.js
curl -L https://unpkg.com/prismjs/components/prism-arff.min.js --create-dirs -o ./doc/static/prismjs/components/prism-arff.min.js
curl -L https://unpkg.com/prismjs/components/prism-asciidoc.min.js --create-dirs -o ./doc/static/prismjs/components/prism-asciidoc.min.js
curl -L https://unpkg.com/prismjs/components/prism-asm6502.min.js --create-dirs -o ./doc/static/prismjs/components/prism-asm6502.min.js
curl -L https://unpkg.com/prismjs/components/prism-aspnet.min.js --create-dirs -o ./doc/static/prismjs/components/prism-aspnet.min.js
curl -L https://unpkg.com/prismjs/components/prism-autohotkey.min.js --create-dirs -o ./doc/static/prismjs/components/prism-autohotkey.min.js
curl -L https://unpkg.com/prismjs/components/prism-autoit.min.js --create-dirs -o ./doc/static/prismjs/components/prism-autoit.min.js
curl -L https://unpkg.com/prismjs/components/prism-bash.min.js --create-dirs -o ./doc/static/prismjs/components/prism-bash.min.js
curl -L https://unpkg.com/prismjs/components/prism-basic.min.js --create-dirs -o ./doc/static/prismjs/components/prism-basic.min.js
curl -L https://unpkg.com/prismjs/components/prism-batch.min.js --create-dirs -o ./doc/static/prismjs/components/prism-batch.min.js
curl -L https://unpkg.com/prismjs/components/prism-bbcode.min.js --create-dirs -o ./doc/static/prismjs/components/prism-bbcode.min.js
curl -L https://unpkg.com/prismjs/components/prism-birb.min.js --create-dirs -o ./doc/static/prismjs/components/prism-birb.min.js
curl -L https://unpkg.com/prismjs/components/prism-bison.min.js --create-dirs -o ./doc/static/prismjs/components/prism-bison.min.js
curl -L https://unpkg.com/prismjs/components/prism-bnf.min.js --create-dirs -o ./doc/static/prismjs/components/prism-bnf.min.js
curl -L https://unpkg.com/prismjs/components/prism-brainfuck.min.js --create-dirs -o ./doc/static/prismjs/components/prism-brainfuck.min.js
curl -L https://unpkg.com/prismjs/components/prism-brightscript.min.js --create-dirs -o ./doc/static/prismjs/components/prism-brightscript.min.js
curl -L https://unpkg.com/prismjs/components/prism-bro.min.js --create-dirs -o ./doc/static/prismjs/components/prism-bro.min.js
curl -L https://unpkg.com/prismjs/components/prism-bsl.min.js --create-dirs -o ./doc/static/prismjs/components/prism-bsl.min.js
curl -L https://unpkg.com/prismjs/components/prism-c.min.js --create-dirs -o ./doc/static/prismjs/components/prism-c.min.js
curl -L https://unpkg.com/prismjs/components/prism-cfscript.min.js --create-dirs -o ./doc/static/prismjs/components/prism-cfscript.min.js
curl -L https://unpkg.com/prismjs/components/prism-chaiscript.min.js --create-dirs -o ./doc/static/prismjs/components/prism-chaiscript.min.js
curl -L https://unpkg.com/prismjs/components/prism-cil.min.js --create-dirs -o ./doc/static/prismjs/components/prism-cil.min.js
curl -L https://unpkg.com/prismjs/components/prism-clike.min.js --create-dirs -o ./doc/static/prismjs/components/prism-clike.min.js
curl -L https://unpkg.com/prismjs/components/prism-clojure.min.js --create-dirs -o ./doc/static/prismjs/components/prism-clojure.min.js
curl -L https://unpkg.com/prismjs/components/prism-cmake.min.js --create-dirs -o ./doc/static/prismjs/components/prism-cmake.min.js
curl -L https://unpkg.com/prismjs/components/prism-cobol.min.js --create-dirs -o ./doc/static/prismjs/components/prism-cobol.min.js
curl -L https://unpkg.com/prismjs/components/prism-coffeescript.min.js --create-dirs -o ./doc/static/prismjs/components/prism-coffeescript.min.js
curl -L https://unpkg.com/prismjs/components/prism-concurnas.min.js --create-dirs -o ./doc/static/prismjs/components/prism-concurnas.min.js
curl -L https://unpkg.com/prismjs/components/prism-coq.min.js --create-dirs -o ./doc/static/prismjs/components/prism-coq.min.js
curl -L https://unpkg.com/prismjs/components/prism-core.min.js --create-dirs -o ./doc/static/prismjs/components/prism-core.min.js
curl -L https://unpkg.com/prismjs/components/prism-cpp.min.js --create-dirs -o ./doc/static/prismjs/components/prism-cpp.min.js
curl -L https://unpkg.com/prismjs/components/prism-crystal.min.js --create-dirs -o ./doc/static/prismjs/components/prism-crystal.min.js
curl -L https://unpkg.com/prismjs/components/prism-csharp.min.js --create-dirs -o ./doc/static/prismjs/components/prism-csharp.min.js
curl -L https://unpkg.com/prismjs/components/prism-csp.min.js --create-dirs -o ./doc/static/prismjs/components/prism-csp.min.js
curl -L https://unpkg.com/prismjs/components/prism-css.min.js --create-dirs -o ./doc/static/prismjs/components/prism-css.min.js
curl -L https://unpkg.com/prismjs/components/prism-css-extras.min.js --create-dirs -o ./doc/static/prismjs/components/prism-css-extras.min.js
curl -L https://unpkg.com/prismjs/components/prism-csv.min.js --create-dirs -o ./doc/static/prismjs/components/prism-csv.min.js
curl -L https://unpkg.com/prismjs/components/prism-cypher.min.js --create-dirs -o ./doc/static/prismjs/components/prism-cypher.min.js
curl -L https://unpkg.com/prismjs/components/prism-d.min.js --create-dirs -o ./doc/static/prismjs/components/prism-d.min.js
curl -L https://unpkg.com/prismjs/components/prism-dart.min.js --create-dirs -o ./doc/static/prismjs/components/prism-dart.min.js
curl -L https://unpkg.com/prismjs/components/prism-dataweave.min.js --create-dirs -o ./doc/static/prismjs/components/prism-dataweave.min.js
curl -L https://unpkg.com/prismjs/components/prism-dax.min.js --create-dirs -o ./doc/static/prismjs/components/prism-dax.min.js
curl -L https://unpkg.com/prismjs/components/prism-dhall.min.js --create-dirs -o ./doc/static/prismjs/components/prism-dhall.min.js
curl -L https://unpkg.com/prismjs/components/prism-diff.min.js --create-dirs -o ./doc/static/prismjs/components/prism-diff.min.js
curl -L https://unpkg.com/prismjs/components/prism-django.min.js --create-dirs -o ./doc/static/prismjs/components/prism-django.min.js
curl -L https://unpkg.com/prismjs/components/prism-dns-zone-file.min.js --create-dirs -o ./doc/static/prismjs/components/prism-dns-zone-file.min.js
curl -L https://unpkg.com/prismjs/components/prism-docker.min.js --create-dirs -o ./doc/static/prismjs/components/prism-docker.min.js
curl -L https://unpkg.com/prismjs/components/prism-dot.min.js --create-dirs -o ./doc/static/prismjs/components/prism-dot.min.js
curl -L https://unpkg.com/prismjs/components/prism-ebnf.min.js --create-dirs -o ./doc/static/prismjs/components/prism-ebnf.min.js
curl -L https://unpkg.com/prismjs/components/prism-editorconfig.min.js --create-dirs -o ./doc/static/prismjs/components/prism-editorconfig.min.js
curl -L https://unpkg.com/prismjs/components/prism-eiffel.min.js --create-dirs -o ./doc/static/prismjs/components/prism-eiffel.min.js
curl -L https://unpkg.com/prismjs/components/prism-ejs.min.js --create-dirs -o ./doc/static/prismjs/components/prism-ejs.min.js
curl -L https://unpkg.com/prismjs/components/prism-elixir.min.js --create-dirs -o ./doc/static/prismjs/components/prism-elixir.min.js
curl -L https://unpkg.com/prismjs/components/prism-elm.min.js --create-dirs -o ./doc/static/prismjs/components/prism-elm.min.js
curl -L https://unpkg.com/prismjs/components/prism-erb.min.js --create-dirs -o ./doc/static/prismjs/components/prism-erb.min.js
curl -L https://unpkg.com/prismjs/components/prism-erlang.min.js --create-dirs -o ./doc/static/prismjs/components/prism-erlang.min.js
curl -L https://unpkg.com/prismjs/components/prism-etlua.min.js --create-dirs -o ./doc/static/prismjs/components/prism-etlua.min.js
curl -L https://unpkg.com/prismjs/components/prism-excel-formula.min.js --create-dirs -o ./doc/static/prismjs/components/prism-excel-formula.min.js
curl -L https://unpkg.com/prismjs/components/prism-factor.min.js --create-dirs -o ./doc/static/prismjs/components/prism-factor.min.js
curl -L https://unpkg.com/prismjs/components/prism-false.min.js --create-dirs -o ./doc/static/prismjs/components/prism-false.min.js
curl -L https://unpkg.com/prismjs/components/prism-firestore-security-rules.min.js --create-dirs -o ./doc/static/prismjs/components/prism-firestore-security-rules.min.js
curl -L https://unpkg.com/prismjs/components/prism-flow.min.js --create-dirs -o ./doc/static/prismjs/components/prism-flow.min.js
curl -L https://unpkg.com/prismjs/components/prism-fortran.min.js --create-dirs -o ./doc/static/prismjs/components/prism-fortran.min.js
curl -L https://unpkg.com/prismjs/components/prism-fsharp.min.js --create-dirs -o ./doc/static/prismjs/components/prism-fsharp.min.js
curl -L https://unpkg.com/prismjs/components/prism-ftl.min.js --create-dirs -o ./doc/static/prismjs/components/prism-ftl.min.js
curl -L https://unpkg.com/prismjs/components/prism-gcode.min.js --create-dirs -o ./doc/static/prismjs/components/prism-gcode.min.js
curl -L https://unpkg.com/prismjs/components/prism-gdscript.min.js --create-dirs -o ./doc/static/prismjs/components/prism-gdscript.min.js
curl -L https://unpkg.com/prismjs/components/prism-gedcom.min.js --create-dirs -o ./doc/static/prismjs/components/prism-gedcom.min.js
curl -L https://unpkg.com/prismjs/components/prism-gherkin.min.js --create-dirs -o ./doc/static/prismjs/components/prism-gherkin.min.js
curl -L https://unpkg.com/prismjs/components/prism-git.min.js --create-dirs -o ./doc/static/prismjs/components/prism-git.min.js
curl -L https://unpkg.com/prismjs/components/prism-glsl.min.js --create-dirs -o ./doc/static/prismjs/components/prism-glsl.min.js
curl -L https://unpkg.com/prismjs/components/prism-gml.min.js --create-dirs -o ./doc/static/prismjs/components/prism-gml.min.js
curl -L https://unpkg.com/prismjs/components/prism-go.min.js --create-dirs -o ./doc/static/prismjs/components/prism-go.min.js
curl -L https://unpkg.com/prismjs/components/prism-graphql.min.js --create-dirs -o ./doc/static/prismjs/components/prism-graphql.min.js
curl -L https://unpkg.com/prismjs/components/prism-groovy.min.js --create-dirs -o ./doc/static/prismjs/components/prism-groovy.min.js
curl -L https://unpkg.com/prismjs/components/prism-haml.min.js --create-dirs -o ./doc/static/prismjs/components/prism-haml.min.js
curl -L https://unpkg.com/prismjs/components/prism-handlebars.min.js --create-dirs -o ./doc/static/prismjs/components/prism-handlebars.min.js
curl -L https://unpkg.com/prismjs/components/prism-haskell.min.js --create-dirs -o ./doc/static/prismjs/components/prism-haskell.min.js
curl -L https://unpkg.com/prismjs/components/prism-haxe.min.js --create-dirs -o ./doc/static/prismjs/components/prism-haxe.min.js
curl -L https://unpkg.com/prismjs/components/prism-hcl.min.js --create-dirs -o ./doc/static/prismjs/components/prism-hcl.min.js
curl -L https://unpkg.com/prismjs/components/prism-hlsl.min.js --create-dirs -o ./doc/static/prismjs/components/prism-hlsl.min.js
curl -L https://unpkg.com/prismjs/components/prism-hpkp.min.js --create-dirs -o ./doc/static/prismjs/components/prism-hpkp.min.js
curl -L https://unpkg.com/prismjs/components/prism-hsts.min.js --create-dirs -o ./doc/static/prismjs/components/prism-hsts.min.js
curl -L https://unpkg.com/prismjs/components/prism-http.min.js --create-dirs -o ./doc/static/prismjs/components/prism-http.min.js
curl -L https://unpkg.com/prismjs/components/prism-ichigojam.min.js --create-dirs -o ./doc/static/prismjs/components/prism-ichigojam.min.js
curl -L https://unpkg.com/prismjs/components/prism-icon.min.js --create-dirs -o ./doc/static/prismjs/components/prism-icon.min.js
curl -L https://unpkg.com/prismjs/components/prism-icu-message-format.min.js --create-dirs -o ./doc/static/prismjs/components/prism-icu-message-format.min.js
curl -L https://unpkg.com/prismjs/components/prism-idris.min.js --create-dirs -o ./doc/static/prismjs/components/prism-idris.min.js
curl -L https://unpkg.com/prismjs/components/prism-iecst.min.js --create-dirs -o ./doc/static/prismjs/components/prism-iecst.min.js
curl -L https://unpkg.com/prismjs/components/prism-ignore.min.js --create-dirs -o ./doc/static/prismjs/components/prism-ignore.min.js
curl -L https://unpkg.com/prismjs/components/prism-inform7.min.js --create-dirs -o ./doc/static/prismjs/components/prism-inform7.min.js
curl -L https://unpkg.com/prismjs/components/prism-ini.min.js --create-dirs -o ./doc/static/prismjs/components/prism-ini.min.js
curl -L https://unpkg.com/prismjs/components/prism-io.min.js --create-dirs -o ./doc/static/prismjs/components/prism-io.min.js
curl -L https://unpkg.com/prismjs/components/prism-j.min.js --create-dirs -o ./doc/static/prismjs/components/prism-j.min.js
curl -L https://unpkg.com/prismjs/components/prism-java.min.js --create-dirs -o ./doc/static/prismjs/components/prism-java.min.js
curl -L https://unpkg.com/prismjs/components/prism-javadoc.min.js --create-dirs -o ./doc/static/prismjs/components/prism-javadoc.min.js
curl -L https://unpkg.com/prismjs/components/prism-javadoclike.min.js --create-dirs -o ./doc/static/prismjs/components/prism-javadoclike.min.js
curl -L https://unpkg.com/prismjs/components/prism-javascript.min.js --create-dirs -o ./doc/static/prismjs/components/prism-javascript.min.js
curl -L https://unpkg.com/prismjs/components/prism-javastacktrace.min.js --create-dirs -o ./doc/static/prismjs/components/prism-javastacktrace.min.js
curl -L https://unpkg.com/prismjs/components/prism-jexl.min.js --create-dirs -o ./doc/static/prismjs/components/prism-jexl.min.js
curl -L https://unpkg.com/prismjs/components/prism-jolie.min.js --create-dirs -o ./doc/static/prismjs/components/prism-jolie.min.js
curl -L https://unpkg.com/prismjs/components/prism-jq.min.js --create-dirs -o ./doc/static/prismjs/components/prism-jq.min.js
curl -L https://unpkg.com/prismjs/components/prism-js-extras.min.js --create-dirs -o ./doc/static/prismjs/components/prism-js-extras.min.js
curl -L https://unpkg.com/prismjs/components/prism-js-templates.min.js --create-dirs -o ./doc/static/prismjs/components/prism-js-templates.min.js
curl -L https://unpkg.com/prismjs/components/prism-jsdoc.min.js --create-dirs -o ./doc/static/prismjs/components/prism-jsdoc.min.js
curl -L https://unpkg.com/prismjs/components/prism-json.min.js --create-dirs -o ./doc/static/prismjs/components/prism-json.min.js
curl -L https://unpkg.com/prismjs/components/prism-json5.min.js --create-dirs -o ./doc/static/prismjs/components/prism-json5.min.js
curl -L https://unpkg.com/prismjs/components/prism-jsonp.min.js --create-dirs -o ./doc/static/prismjs/components/prism-jsonp.min.js
curl -L https://unpkg.com/prismjs/components/prism-jsstacktrace.min.js --create-dirs -o ./doc/static/prismjs/components/prism-jsstacktrace.min.js
curl -L https://unpkg.com/prismjs/components/prism-jsx.min.js --create-dirs -o ./doc/static/prismjs/components/prism-jsx.min.js
curl -L https://unpkg.com/prismjs/components/prism-julia.min.js --create-dirs -o ./doc/static/prismjs/components/prism-julia.min.js
curl -L https://unpkg.com/prismjs/components/prism-keyman.min.js --create-dirs -o ./doc/static/prismjs/components/prism-keyman.min.js
curl -L https://unpkg.com/prismjs/components/prism-kotlin.min.js --create-dirs -o ./doc/static/prismjs/components/prism-kotlin.min.js
curl -L https://unpkg.com/prismjs/components/prism-kumir.min.js --create-dirs -o ./doc/static/prismjs/components/prism-kumir.min.js
curl -L https://unpkg.com/prismjs/components/prism-latex.min.js --create-dirs -o ./doc/static/prismjs/components/prism-latex.min.js
curl -L https://unpkg.com/prismjs/components/prism-latte.min.js --create-dirs -o ./doc/static/prismjs/components/prism-latte.min.js
curl -L https://unpkg.com/prismjs/components/prism-less.min.js --create-dirs -o ./doc/static/prismjs/components/prism-less.min.js
curl -L https://unpkg.com/prismjs/components/prism-lilypond.min.js --create-dirs -o ./doc/static/prismjs/components/prism-lilypond.min.js
curl -L https://unpkg.com/prismjs/components/prism-liquid.min.js --create-dirs -o ./doc/static/prismjs/components/prism-liquid.min.js
curl -L https://unpkg.com/prismjs/components/prism-lisp.min.js --create-dirs -o ./doc/static/prismjs/components/prism-lisp.min.js
curl -L https://unpkg.com/prismjs/components/prism-livescript.min.js --create-dirs -o ./doc/static/prismjs/components/prism-livescript.min.js
curl -L https://unpkg.com/prismjs/components/prism-llvm.min.js --create-dirs -o ./doc/static/prismjs/components/prism-llvm.min.js
curl -L https://unpkg.com/prismjs/components/prism-log.min.js --create-dirs -o ./doc/static/prismjs/components/prism-log.min.js
curl -L https://unpkg.com/prismjs/components/prism-lolcode.min.js --create-dirs -o ./doc/static/prismjs/components/prism-lolcode.min.js
curl -L https://unpkg.com/prismjs/components/prism-lua.min.js --create-dirs -o ./doc/static/prismjs/components/prism-lua.min.js
curl -L https://unpkg.com/prismjs/components/prism-makefile.min.js --create-dirs -o ./doc/static/prismjs/components/prism-makefile.min.js
curl -L https://unpkg.com/prismjs/components/prism-markdown.min.js --create-dirs -o ./doc/static/prismjs/components/prism-markdown.min.js
curl -L https://unpkg.com/prismjs/components/prism-markup.min.js --create-dirs -o ./doc/static/prismjs/components/prism-markup.min.js
curl -L https://unpkg.com/prismjs/components/prism-markup-templating.min.js --create-dirs -o ./doc/static/prismjs/components/prism-markup-templating.min.js
curl -L https://unpkg.com/prismjs/components/prism-matlab.min.js --create-dirs -o ./doc/static/prismjs/components/prism-matlab.min.js
curl -L https://unpkg.com/prismjs/components/prism-mel.min.js --create-dirs -o ./doc/static/prismjs/components/prism-mel.min.js
curl -L https://unpkg.com/prismjs/components/prism-mizar.min.js --create-dirs -o ./doc/static/prismjs/components/prism-mizar.min.js
curl -L https://unpkg.com/prismjs/components/prism-mongodb.min.js --create-dirs -o ./doc/static/prismjs/components/prism-mongodb.min.js
curl -L https://unpkg.com/prismjs/components/prism-monkey.min.js --create-dirs -o ./doc/static/prismjs/components/prism-monkey.min.js
curl -L https://unpkg.com/prismjs/components/prism-moonscript.min.js --create-dirs -o ./doc/static/prismjs/components/prism-moonscript.min.js
curl -L https://unpkg.com/prismjs/components/prism-n1ql.min.js --create-dirs -o ./doc/static/prismjs/components/prism-n1ql.min.js
curl -L https://unpkg.com/prismjs/components/prism-n4js.min.js --create-dirs -o ./doc/static/prismjs/components/prism-n4js.min.js
curl -L https://unpkg.com/prismjs/components/prism-nand2tetris-hdl.min.js --create-dirs -o ./doc/static/prismjs/components/prism-nand2tetris-hdl.min.js
curl -L https://unpkg.com/prismjs/components/prism-naniscript.min.js --create-dirs -o ./doc/static/prismjs/components/prism-naniscript.min.js
curl -L https://unpkg.com/prismjs/components/prism-nasm.min.js --create-dirs -o ./doc/static/prismjs/components/prism-nasm.min.js
curl -L https://unpkg.com/prismjs/components/prism-neon.min.js --create-dirs -o ./doc/static/prismjs/components/prism-neon.min.js
curl -L https://unpkg.com/prismjs/components/prism-nevod.min.js --create-dirs -o ./doc/static/prismjs/components/prism-nevod.min.js
curl -L https://unpkg.com/prismjs/components/prism-nginx.min.js --create-dirs -o ./doc/static/prismjs/components/prism-nginx.min.js
curl -L https://unpkg.com/prismjs/components/prism-nim.min.js --create-dirs -o ./doc/static/prismjs/components/prism-nim.min.js
curl -L https://unpkg.com/prismjs/components/prism-nix.min.js --create-dirs -o ./doc/static/prismjs/components/prism-nix.min.js
curl -L https://unpkg.com/prismjs/components/prism-nsis.min.js --create-dirs -o ./doc/static/prismjs/components/prism-nsis.min.js
curl -L https://unpkg.com/prismjs/components/prism-objectivec.min.js --create-dirs -o ./doc/static/prismjs/components/prism-objectivec.min.js
curl -L https://unpkg.com/prismjs/components/prism-ocaml.min.js --create-dirs -o ./doc/static/prismjs/components/prism-ocaml.min.js
curl -L https://unpkg.com/prismjs/components/prism-opencl.min.js --create-dirs -o ./doc/static/prismjs/components/prism-opencl.min.js
curl -L https://unpkg.com/prismjs/components/prism-openqasm.min.js --create-dirs -o ./doc/static/prismjs/components/prism-openqasm.min.js
curl -L https://unpkg.com/prismjs/components/prism-oz.min.js --create-dirs -o ./doc/static/prismjs/components/prism-oz.min.js
curl -L https://unpkg.com/prismjs/components/prism-parigp.min.js --create-dirs -o ./doc/static/prismjs/components/prism-parigp.min.js
curl -L https://unpkg.com/prismjs/components/prism-parser.min.js --create-dirs -o ./doc/static/prismjs/components/prism-parser.min.js
curl -L https://unpkg.com/prismjs/components/prism-pascal.min.js --create-dirs -o ./doc/static/prismjs/components/prism-pascal.min.js
curl -L https://unpkg.com/prismjs/components/prism-pascaligo.min.js --create-dirs -o ./doc/static/prismjs/components/prism-pascaligo.min.js
curl -L https://unpkg.com/prismjs/components/prism-pcaxis.min.js --create-dirs -o ./doc/static/prismjs/components/prism-pcaxis.min.js
curl -L https://unpkg.com/prismjs/components/prism-peoplecode.min.js --create-dirs -o ./doc/static/prismjs/components/prism-peoplecode.min.js
curl -L https://unpkg.com/prismjs/components/prism-perl.min.js --create-dirs -o ./doc/static/prismjs/components/prism-perl.min.js
curl -L https://unpkg.com/prismjs/components/prism-php.min.js --create-dirs -o ./doc/static/prismjs/components/prism-php.min.js
curl -L https://unpkg.com/prismjs/components/prism-php-extras.min.js --create-dirs -o ./doc/static/prismjs/components/prism-php-extras.min.js
curl -L https://unpkg.com/prismjs/components/prism-phpdoc.min.js --create-dirs -o ./doc/static/prismjs/components/prism-phpdoc.min.js
curl -L https://unpkg.com/prismjs/components/prism-plsql.min.js --create-dirs -o ./doc/static/prismjs/components/prism-plsql.min.js
curl -L https://unpkg.com/prismjs/components/prism-powerquery.min.js --create-dirs -o ./doc/static/prismjs/components/prism-powerquery.min.js
curl -L https://unpkg.com/prismjs/components/prism-powershell.min.js --create-dirs -o ./doc/static/prismjs/components/prism-powershell.min.js
curl -L https://unpkg.com/prismjs/components/prism-processing.min.js --create-dirs -o ./doc/static/prismjs/components/prism-processing.min.js
curl -L https://unpkg.com/prismjs/components/prism-prolog.min.js --create-dirs -o ./doc/static/prismjs/components/prism-prolog.min.js
curl -L https://unpkg.com/prismjs/components/prism-promql.min.js --create-dirs -o ./doc/static/prismjs/components/prism-promql.min.js
curl -L https://unpkg.com/prismjs/components/prism-properties.min.js --create-dirs -o ./doc/static/prismjs/components/prism-properties.min.js
curl -L https://unpkg.com/prismjs/components/prism-protobuf.min.js --create-dirs -o ./doc/static/prismjs/components/prism-protobuf.min.js
curl -L https://unpkg.com/prismjs/components/prism-psl.min.js --create-dirs -o ./doc/static/prismjs/components/prism-psl.min.js
curl -L https://unpkg.com/prismjs/components/prism-pug.min.js --create-dirs -o ./doc/static/prismjs/components/prism-pug.min.js
curl -L https://unpkg.com/prismjs/components/prism-puppet.min.js --create-dirs -o ./doc/static/prismjs/components/prism-puppet.min.js
curl -L https://unpkg.com/prismjs/components/prism-pure.min.js --create-dirs -o ./doc/static/prismjs/components/prism-pure.min.js
curl -L https://unpkg.com/prismjs/components/prism-purebasic.min.js --create-dirs -o ./doc/static/prismjs/components/prism-purebasic.min.js
curl -L https://unpkg.com/prismjs/components/prism-purescript.min.js --create-dirs -o ./doc/static/prismjs/components/prism-purescript.min.js
curl -L https://unpkg.com/prismjs/components/prism-python.min.js --create-dirs -o ./doc/static/prismjs/components/prism-python.min.js
curl -L https://unpkg.com/prismjs/components/prism-q.min.js --create-dirs -o ./doc/static/prismjs/components/prism-q.min.js
curl -L https://unpkg.com/prismjs/components/prism-qml.min.js --create-dirs -o ./doc/static/prismjs/components/prism-qml.min.js
curl -L https://unpkg.com/prismjs/components/prism-qore.min.js --create-dirs -o ./doc/static/prismjs/components/prism-qore.min.js
curl -L https://unpkg.com/prismjs/components/prism-qsharp.min.js --create-dirs -o ./doc/static/prismjs/components/prism-qsharp.min.js
curl -L https://unpkg.com/prismjs/components/prism-r.min.js --create-dirs -o ./doc/static/prismjs/components/prism-r.min.js
curl -L https://unpkg.com/prismjs/components/prism-racket.min.js --create-dirs -o ./doc/static/prismjs/components/prism-racket.min.js
curl -L https://unpkg.com/prismjs/components/prism-reason.min.js --create-dirs -o ./doc/static/prismjs/components/prism-reason.min.js
curl -L https://unpkg.com/prismjs/components/prism-regex.min.js --create-dirs -o ./doc/static/prismjs/components/prism-regex.min.js
curl -L https://unpkg.com/prismjs/components/prism-rego.min.js --create-dirs -o ./doc/static/prismjs/components/prism-rego.min.js
curl -L https://unpkg.com/prismjs/components/prism-renpy.min.js --create-dirs -o ./doc/static/prismjs/components/prism-renpy.min.js
curl -L https://unpkg.com/prismjs/components/prism-rest.min.js --create-dirs -o ./doc/static/prismjs/components/prism-rest.min.js
curl -L https://unpkg.com/prismjs/components/prism-rip.min.js --create-dirs -o ./doc/static/prismjs/components/prism-rip.min.js
curl -L https://unpkg.com/prismjs/components/prism-roboconf.min.js --create-dirs -o ./doc/static/prismjs/components/prism-roboconf.min.js
curl -L https://unpkg.com/prismjs/components/prism-robotframework.min.js --create-dirs -o ./doc/static/prismjs/components/prism-robotframework.min.js
curl -L https://unpkg.com/prismjs/components/prism-ruby.min.js --create-dirs -o ./doc/static/prismjs/components/prism-ruby.min.js
curl -L https://unpkg.com/prismjs/components/prism-rust.min.js --create-dirs -o ./doc/static/prismjs/components/prism-rust.min.js
curl -L https://unpkg.com/prismjs/components/prism-sas.min.js --create-dirs -o ./doc/static/prismjs/components/prism-sas.min.js
curl -L https://unpkg.com/prismjs/components/prism-sass.min.js --create-dirs -o ./doc/static/prismjs/components/prism-sass.min.js
curl -L https://unpkg.com/prismjs/components/prism-scala.min.js --create-dirs -o ./doc/static/prismjs/components/prism-scala.min.js
curl -L https://unpkg.com/prismjs/components/prism-scheme.min.js --create-dirs -o ./doc/static/prismjs/components/prism-scheme.min.js
curl -L https://unpkg.com/prismjs/components/prism-scss.min.js --create-dirs -o ./doc/static/prismjs/components/prism-scss.min.js
curl -L https://unpkg.com/prismjs/components/prism-shell-session.min.js --create-dirs -o ./doc/static/prismjs/components/prism-shell-session.min.js
curl -L https://unpkg.com/prismjs/components/prism-smali.min.js --create-dirs -o ./doc/static/prismjs/components/prism-smali.min.js
curl -L https://unpkg.com/prismjs/components/prism-smalltalk.min.js --create-dirs -o ./doc/static/prismjs/components/prism-smalltalk.min.js
curl -L https://unpkg.com/prismjs/components/prism-smarty.min.js --create-dirs -o ./doc/static/prismjs/components/prism-smarty.min.js
curl -L https://unpkg.com/prismjs/components/prism-sml.min.js --create-dirs -o ./doc/static/prismjs/components/prism-sml.min.js
curl -L https://unpkg.com/prismjs/components/prism-solidity.min.js --create-dirs -o ./doc/static/prismjs/components/prism-solidity.min.js
curl -L https://unpkg.com/prismjs/components/prism-solution-file.min.js --create-dirs -o ./doc/static/prismjs/components/prism-solution-file.min.js
curl -L https://unpkg.com/prismjs/components/prism-soy.min.js --create-dirs -o ./doc/static/prismjs/components/prism-soy.min.js
curl -L https://unpkg.com/prismjs/components/prism-sparql.min.js --create-dirs -o ./doc/static/prismjs/components/prism-sparql.min.js
curl -L https://unpkg.com/prismjs/components/prism-splunk-spl.min.js --create-dirs -o ./doc/static/prismjs/components/prism-splunk-spl.min.js
curl -L https://unpkg.com/prismjs/components/prism-sqf.min.js --create-dirs -o ./doc/static/prismjs/components/prism-sqf.min.js
curl -L https://unpkg.com/prismjs/components/prism-sql.min.js --create-dirs -o ./doc/static/prismjs/components/prism-sql.min.js
curl -L https://unpkg.com/prismjs/components/prism-squirrel.min.js --create-dirs -o ./doc/static/prismjs/components/prism-squirrel.min.js
curl -L https://unpkg.com/prismjs/components/prism-stan.min.js --create-dirs -o ./doc/static/prismjs/components/prism-stan.min.js
curl -L https://unpkg.com/prismjs/components/prism-stylus.min.js --create-dirs -o ./doc/static/prismjs/components/prism-stylus.min.js
curl -L https://unpkg.com/prismjs/components/prism-swift.min.js --create-dirs -o ./doc/static/prismjs/components/prism-swift.min.js
curl -L https://unpkg.com/prismjs/components/prism-t4-cs.min.js --create-dirs -o ./doc/static/prismjs/components/prism-t4-cs.min.js
curl -L https://unpkg.com/prismjs/components/prism-t4-templating.min.js --create-dirs -o ./doc/static/prismjs/components/prism-t4-templating.min.js
curl -L https://unpkg.com/prismjs/components/prism-t4-vb.min.js --create-dirs -o ./doc/static/prismjs/components/prism-t4-vb.min.js
curl -L https://unpkg.com/prismjs/components/prism-tap.min.js --create-dirs -o ./doc/static/prismjs/components/prism-tap.min.js
curl -L https://unpkg.com/prismjs/components/prism-tcl.min.js --create-dirs -o ./doc/static/prismjs/components/prism-tcl.min.js
curl -L https://unpkg.com/prismjs/components/prism-textile.min.js --create-dirs -o ./doc/static/prismjs/components/prism-textile.min.js
curl -L https://unpkg.com/prismjs/components/prism-toml.min.js --create-dirs -o ./doc/static/prismjs/components/prism-toml.min.js
curl -L https://unpkg.com/prismjs/components/prism-tsx.min.js --create-dirs -o ./doc/static/prismjs/components/prism-tsx.min.js
curl -L https://unpkg.com/prismjs/components/prism-tt2.min.js --create-dirs -o ./doc/static/prismjs/components/prism-tt2.min.js
curl -L https://unpkg.com/prismjs/components/prism-turtle.min.js --create-dirs -o ./doc/static/prismjs/components/prism-turtle.min.js
curl -L https://unpkg.com/prismjs/components/prism-twig.min.js --create-dirs -o ./doc/static/prismjs/components/prism-twig.min.js
curl -L https://unpkg.com/prismjs/components/prism-typescript.min.js --create-dirs -o ./doc/static/prismjs/components/prism-typescript.min.js
curl -L https://unpkg.com/prismjs/components/prism-typoscript.min.js --create-dirs -o ./doc/static/prismjs/components/prism-typoscript.min.js
curl -L https://unpkg.com/prismjs/components/prism-unrealscript.min.js --create-dirs -o ./doc/static/prismjs/components/prism-unrealscript.min.js
curl -L https://unpkg.com/prismjs/components/prism-uri.min.js --create-dirs -o ./doc/static/prismjs/components/prism-uri.min.js
curl -L https://unpkg.com/prismjs/components/prism-v.min.js --create-dirs -o ./doc/static/prismjs/components/prism-v.min.js
curl -L https://unpkg.com/prismjs/components/prism-vala.min.js --create-dirs -o ./doc/static/prismjs/components/prism-vala.min.js
curl -L https://unpkg.com/prismjs/components/prism-vbnet.min.js --create-dirs -o ./doc/static/prismjs/components/prism-vbnet.min.js
curl -L https://unpkg.com/prismjs/components/prism-velocity.min.js --create-dirs -o ./doc/static/prismjs/components/prism-velocity.min.js
curl -L https://unpkg.com/prismjs/components/prism-verilog.min.js --create-dirs -o ./doc/static/prismjs/components/prism-verilog.min.js
curl -L https://unpkg.com/prismjs/components/prism-vhdl.min.js --create-dirs -o ./doc/static/prismjs/components/prism-vhdl.min.js
curl -L https://unpkg.com/prismjs/components/prism-vim.min.js --create-dirs -o ./doc/static/prismjs/components/prism-vim.min.js
curl -L https://unpkg.com/prismjs/components/prism-visual-basic.min.js --create-dirs -o ./doc/static/prismjs/components/prism-visual-basic.min.js
curl -L https://unpkg.com/prismjs/components/prism-warpscript.min.js --create-dirs -o ./doc/static/prismjs/components/prism-warpscript.min.js
curl -L https://unpkg.com/prismjs/components/prism-wasm.min.js --create-dirs -o ./doc/static/prismjs/components/prism-wasm.min.js
curl -L https://unpkg.com/prismjs/components/prism-wiki.min.js --create-dirs -o ./doc/static/prismjs/components/prism-wiki.min.js
curl -L https://unpkg.com/prismjs/components/prism-wolfram.min.js --create-dirs -o ./doc/static/prismjs/components/prism-wolfram.min.js
curl -L https://unpkg.com/prismjs/components/prism-xeora.min.js --create-dirs -o ./doc/static/prismjs/components/prism-xeora.min.js
curl -L https://unpkg.com/prismjs/components/prism-xml-doc.min.js --create-dirs -o ./doc/static/prismjs/components/prism-xml-doc.min.js
curl -L https://unpkg.com/prismjs/components/prism-xojo.min.js --create-dirs -o ./doc/static/prismjs/components/prism-xojo.min.js
curl -L https://unpkg.com/prismjs/components/prism-xquery.min.js --create-dirs -o ./doc/static/prismjs/components/prism-xquery.min.js
curl -L https://unpkg.com/prismjs/components/prism-yaml.min.js --create-dirs -o ./doc/static/prismjs/components/prism-yaml.min.js
curl -L https://unpkg.com/prismjs/components/prism-yang.min.js --create-dirs -o ./doc/static/prismjs/components/prism-yang.min.js
curl -L https://unpkg.com/prismjs/components/prism-zig.min.js --create-dirs -o ./doc/static/prismjs/components/prism-zig.min.js